DROP TABLE IF EXISTS TEAMMEMBERS;
  
CREATE TABLE TEAMMEMBERS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  lastName VARCHAR(250) NOT NULL,
  rol VARCHAR(250) DEFAULT NULL
);

DROP TABLE IF EXISTS PROJECTS;
  
CREATE TABLE PROJECTS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  projectName VARCHAR(250) NOT NULL,
  codeID VARCHAR(250) NOT NULL,
  descripcion VARCHAR(250) DEFAULT NULL
);